### ISSUE TITLE
delegate=True 

### ISSUE THREAD

**Issue by joakim-tjernlund** [openSUSE/cepces#4]
In commit https://github.com/openSUSE/cepces/commit/ec43940de38e3b23192552ecc185476937013e8e
delegate=True is hardcoded. I wonder if that sensible choice for everyone?
Perhaps a config knob instead?

**Comment by joakim-tjernlund** [comment]
I do not speak python so no PR from me :(
Does  CVE-2020-17049 has any bearing on cepces w.r.t delegation ?

**Comment by dmulder** [comment]
@Tuurtje and @joakim-tjernlund I'll look at adding a configuration option for this.

**Comment by dmulder** [comment]
> Does CVE-2020-17049 has any bearing on cepces w.r.t delegation ?
CVE-2020-17049 was fixed by causing the KDC to sign tickets in a S4U2self exchange (and the signature is in the PAC, and protected from alternation). Later, in an S4U2proxy exchange (during delegation), the KDC validates that signature to ensure the service didn't modify the ticket (flipping the forwardable bit).
Since CVE-2020-17049 is fixed by taking extra precautions in the KDC, it isn't really relevant here.

**Comment by dmulder** [comment]
@joakim-tjernlund would you be able to test the changes in mr #7?
